---
ip            : 127.0.0.1
port          : 8000
hostname      : mac-one.tumblr.com
CHECK_INTERVAL: 5
log_file      : httpd_check.log
ZkNode:
  connect_string: 127.0.0.1:2181
  parent_dir    : /webs
HttpCheck:
  port: 8000
  uri : /index.html